### ISSUE TITLE
running your project

### ISSUE THREAD

**Issue by mg64ve** [kamiyaa/website-wasm#1]
Hi nice idea, I want to study your code.
Thanks for sharing.
I have done the following:

```
cargo install wasm-pack
sh ./build.sh
sh run.sh
```

But I am getting the following:

![image](https://user-images.githubusercontent.com/22278227/104109181-aed58680-52cb-11eb-972b-e442732063a3.png)

which I don't think has the same rendering.
Am I missing anything?

**Comment by kamiyaa** [comment]
Hey @mg64ve,

I wasn't super clear in the build instructions.
I've updated the build instructions to compile the sass as well here: e34c48d1e4ad085b3adb45e394df5f19365a2ab7

Cheers

**Comment by mg64ve** [comment]
Thanks @kamiyaa .
I am missing 'sassc'.
What is that?

**Comment by kamiyaa** [comment]
Its a sass to css command line compiler (https://github.com/sass/sassc).
You can probably install it through your package manager.
My css was written in sass so I have to compile it to css.

I've included a precompiled version of `index.css` which you can place inside `static/css` as `index.css` if you don't have sassc installed.

(renamed to index.txt because github doesn't allow css attachments)
[index.txt](https://github.com/kamiyaa/website-wasm/files/5791901/index.txt)

**Comment by mg64ve** [comment]
ok, it works now @kamiyaa 
Thanks a lot.
Cheers
